server:
  port: 8087
  servlet:
    context-path: /resumeProject

#数据库
spring:
  datasource:
    url: jdbc:mysql://123.60.99.253:3306/resume?allowPublicKeyRetrieval=true&characterEncoding=utf-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: wyf542199
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置slq打印日志 （方式二）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl